### ISSUE TITLE
Scroll issue in DayView

### ISSUE THREAD

**Issue by ronny-strath** [SimformSolutionsPvtLtd/flutter_calendar_view#312]
I'm experiencing an issue with DayView in my app.
I have a tab bar to switch between views, and a couple of events to show in the views. The events display an AlertDialog when tapped, using the onEventTap property.
Everything works fine in MonthView and WeekView, but in DayView the AlertDialog only works if I tap the event without doing any scrolling. When trying to scroll, the view is very slow to respond and doesn't scroll smoothly like in the other views. Once some scrolling has been done, tapping the event doesn't open the AlertDialog anymore.

The only error I see in the console happens when I switch from DayView to a different view:
`E/flutter (23698): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 201 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
E/flutter (23698): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (23698): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (23698): #2      ScrollController.animateTo (package:flutter/src/widgets/scroll_controller.dart:201:12)
E/flutter (23698): #3      DayViewState.animateToDuration (package:calendar_view/src/day_view/day_view.dart:803:23)
E/flutter (23698): #4      DayViewState.didChangeDependencies.<anonymous closure> (package:calendar_view/src/day_view/day_view.dart:328:7)
E/flutter (23698): #5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
E/flutter (23698): #6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1264:9)
E/flutter (23698): #7      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
E/flutter (23698): #8      _invoke (dart:ui/hooks.dart:312:13)
E/flutter (23698): #9      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
E/flutter (23698): #10     _drawFrame (dart:ui/hooks.dart:283:31)`

I've attached my main.dart file. Can you please let me know if there's something I'm doing wrong?
[main.dart.txt](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/files/14083032/main.dart.txt)

**Comment by ronny-strath** [comment]
Sorry - I figured out it was to do with how I loaded the json data. Have changed my code to call the readJson() method inside initState instead of in the widget's build method and it works ok now.
